import Head from 'next/head'
import { Inter } from 'next/font/google'
import Layout from './components/Layout'
import Image from 'next/image'
import profilePic from '../../public/images/profile/d1.jpeg'
import AnimatedText from './components/AnimatedText'
import Link from 'next/link'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className='flex items-center text-dark w-full min-h-screen'>
       <Layout className='pt-0'>
        <div className='flex items-center justify-between w-full'>
          <div className='w-1/2'>
            <Image src={profilePic} alt='DominicMena' className='w-auto h-full'/>
          </div>
          <div className='w-1/2 flex flex-col items-center self-center'>
            <AnimatedText text='Software Engineer' className='!text-6xl !text-left'/>
            <p className='my-4 text-base font-medium'>
          Dominic Mena was born and raised in El, Paso TX - A lifelong learner, he recieved his B.A. in Philosophy from Arizona State and went on to work for DoorDash in it's start-up days - scaling up multiple facets of the company for 5+ years.  When not researching new methods for code; Playing music, going for runs, reading and spending time with my girlfriend are favorite pastimes.
        </p>
        <div>
          <Link href='/dummy.pdf' target="_blank">Resume</Link>
          <Link href='mailto:mena.dominic@gmail.com' target='_blank'>Contact</Link>
        </div>
          </div>
        </div>
       </Layout>
      </main>
    </>
  )
}
