import React from "react";
import Head from "next/head";
import Layout from "./components/Layout";
import AnimatedText from "./components/AnimatedText";
import Link from "next/link";
import GitIcon from "./components/Icons";
import Image from "next/image";
import project1 from '../../public/images/projects/crypto-screener-cover-image.jpg'

const FeaturedProject = ({type, title, summary, img, link, github}) => {

    return(
<article>
    <Link href={link} target='_blank'>
    <Image src={img} alt={title} className='w-full h-auto'/>
    </Link>

    <div>
        <span>{type}</span>
        <Link href={link} target='_blank'>
        <h2>{title}</h2>

        </Link>
        <p>{summary}</p>
        <div>
            <Link href={github} target='_blank'> <GitIcon/> </Link>
            <Link href={link} target='_blank'> Visit Project </Link>
        </div>
    </div>
    </article>
    )
}

const projects = () => {
    return ( 
        <>
        <Head>
        <title>Dominic Mena | Projects Page </title>
        <meta name="description" content="Generated by create next app" />
      </Head>
<main className="w-full mb-16 flex flex-col items-center justify-center">
    <Layout className='pt-16'>
        <AnimatedText text='Code today, innovate tomorrow'/>

        <div className="grid grid-cols-12 gap-24">
            <div className="col-span-12">
                <FeaturedProject
                
                title="Vinyl Shop & Archive"
                img={project1}
                summary="The vinyl shopping experience of the future"
                link='/'
                github={'/'}
                type="Featured Project"
                
                />
            </div>
            <div className="col-span-6">
                Project-1
            </div>
            <div className="col-span-6">
                Project-2
            </div>
            <div className="col-span-12">
                Featured Project
            </div>
            <div className="col-span-6">
                Project-3
            </div>
            <div className="col-span-6">
                Project-4
            </div>
        </div>
    </Layout>
    </main>

</>
     );
}
 
export default projects;